### ISSUE TITLE
implement jwt auth via firebase client-side

### ISSUE THREAD

**Issue by jerrydngzh** [jerrydngzh/372.projdev#26]
- add in firebase auth client side
- integrate w/ signin/signup flow
- sends request w/ jwt token to backend, backend will verifying that token as middleware

resources:
- [firebase auth tokens, client vs admin sdk | Medium](https://medium.com/@jwngr/demystifying-firebase-auth-tokens-e0c533ed330c)

**Comment by Toastjpg** [comment]
It might be overkill and a waste of your time to authenticate requests in the backend with a JWT. There is no security requirement in this project so public API is fine imo. 

However proper login at the very least with firebase auth is a good so we no longer store plain text passwords...
