### ISSUE TITLE
deploymnet: setup cloud storage cdn for media uploads

### ISSUE THREAD

**Issue by jerrydngzh** [jerrydngzh/372.projdev#40]
blocked/dependent on #33 & #35

- setup a cdn for media uploads
- secure media uploads & control access who can view particular media uploaded
   - i.e. only the user that uploads it can see it

**Comment by Toastjpg** [comment]
do we need a CDN? media uploads are stored as media types in mongo

This might be overkill for our app

**Comment by jerrydngzh** [comment]
ah didnt look closely into how media files are currently stored
- this does come at an issue with scalability however, as we currently rely on a free version (correct me if im wrong) of atlas, that charges high cost per storage used compared to other cloud storage providers

- having a cloud storage bucket for example would be more appropriate

**Comment by Toastjpg** [comment]
The current tier of Mongo atlas we use (M0) has a 500 mb limit for storage. There are limits on concurrent read/writes and connections, but no limit on a number of read/writes.

From here: https://www.mongodb.com/pricing

**Comment by Toastjpg** [comment]
I think there was also a misunderstanding on my part when discussing the media features w/ @Leepak777. I think media should be limited to 5, so only images and no video since we only have 500 mb.

**Comment by Toastjpg** [comment]
Alternatively we can just move off to Firestore lol?

**Comment by jerrydngzh** [comment]
500mb runs it very quickly if we're accounting for media uploads in that case, especially as #33 handles video, audio and images. 
Image quality is a factor into this as well. Regardless if we have a limit to image uploads, we dont have a limit to the number of memos = 5*n.

**Comment by Toastjpg** [comment]
Ive left a comment in the PR to suggest a change to media to only support images under 5mb.
