### ISSUE TITLE
admin page + features

### ISSUE THREAD

**Issue by Toastjpg** [jerrydngzh/372.projdev#44]
Need to add different type of role in addition to the normal user.

Will implement Admin role + Admin page.

Admin will have access to a page where they are able to use the get all endpoints for all the services.
Thats about it. This is just to satisfy the project requirements.

**Comment by Toastjpg** [comment]
i looked into adding proper admin roles to a user but it seems like that uses the firebase admin sdk

as an alternative to checking if user is the admin, perhaps storing the admin user account uid in an environment variable and checking that value on login? Route to an admin page if true, else route to dashboard or something

**Comment by jerrydngzh** [comment]
perhaps a admin role w/ a panel to view all, categorized by users, in addition to deleting the user / memos
