### ISSUE TITLE
refactor & streamline the interactions of our backend services

### ISSUE THREAD

**Issue by jerrydngzh** [jerrydngzh/372.projdev#57]
currently our backend services are fairly isolated, meaning any logical sequence of operations that involve both the memo & user service are handled as separate calls from the client.
- we were being fine-grained, but too overtly fine-grained in this case
- this [stackoverflow response](https://stackoverflow.com/questions/32256931/two-way-communication-between-routers-within-express-app) presents a good way of approaching our use of routes vs services for expressjs and the coupling between them
- ex:
  ```tsx
  // CreateMemo.tsx, handleSubmit()
  ...
        const createdMemo = await MemoController.create_memo(currentUser.uid, memoToCreate);
        const newMemoId = createdMemo._id;
  
        let newUserData: any = userData;
        newUserData.memos = [...userData.memos, newMemoId];
  
        const user = await UserController.update_user(currentUser.uid, newUserData);
  ...
  ```
  - should the client succeed on creating a memo, then fail updating the user with the returned `memo_id`, the system will be left in a inconsistent state.

Our backend services also do not expose appropriate types of the result they return. On the client-side project, most of our backend calls  return a `Promise<any>` if not specified the return object type.

**Comment by Toastjpg** [comment]
Wait why do we need to update a list of memo _id in the user anyways? The backend MemoService already has an endpoint for get/:user_id that returns all memos a specific user has created.

**Comment by jerrydngzh** [comment]
Yeah we shouldn't, that is it's own can of worms in #58

But I guess point being that the proper way of doing should be that when we create a memo, it should also update the user on the backend vs telling the client to do it. 
 - when we create a memo, it only adds to the memo collection on the backend 
 - having the client deal with this second transitive step leaves inconsistencies when it fails -- in hindsight creating a memo is transaction that should either succeed or fail

**Comment by Toastjpg** [comment]
Ok then the UserService schema shouldnt keep a list of memos then if we can already get memos by a uid.

I dont see the problem here?

**Comment by jerrydngzh** [comment]
Yes, the problem is actually that User Schema shouldn't have a list of memos.
