### ISSUE TITLE
logic in creating a memo in `CreateMemo` is broken

### ISSUE THREAD

**Issue by jerrydngzh** [jerrydngzh/372.projdev#58]
currently the CreateMemo component doesnt have access to the client's version of user data (and memos)
- the problem lies in that no props are specified in the component for using a parent components' state of user data/memo list
   - which means that we're always sending a `UserType` object with an empty memo list + the new the new memo_id
   - the backend service for updating a user, expects a user's previous state + the new state by taking the body wholely and updating the user as-is
   - i.e. we're overwriting values, not updating it 

__BLOCKING:__
 - Changes will need to be made seen or have confirmed to exist on a higher-level component such as `components/Dashboard/` or making use of contexts with maintaining the state of user data + memos before this change can be done
 
while it is *okay* to make separate calls for creating a memo then a call to update the user, changes on the backend will be dealt in the future (see #57)

**Comment by Leepak777** [comment]
Since Dashboard is on the same level as createMemo, should I make a user Context that stores the userData, and functions to update specific fields?

**Comment by Toastjpg** [comment]
https://github.com/jerrydngzh/372.projdev/issues/57#issuecomment-2041661499

Remove the dependencies between UserService and MemoService then. So we dont need to be updating the User objects.

**Comment by jerrydngzh** [comment]
Yeah remove the need to update the user via the frontend, that should be handled on the backend when creating a memo. 

There are some options on how we can approach now displaying the set of newly updated memos for a user on navigation back to the dashboard:
1. dashboard makes a get request for new data 
    -> easiest, but lots of data fetching if we only changed 1 thing
2. we maintain a list of memos on the frontend on initial load and manage adding/deleting from that via our different pages
    -> ***more*** complex, requires state management especially given we're using `react-router-dom`, but we only do data fetch/updates that are necessary

**Comment by Leepak777** [comment]
from what i see instead of reading user memos array fetch one by one , use the memo controller get_all_memos right? then there shouldn't be necessary to maintain a list?

**Comment by jerrydngzh** [comment]
We shouldn't even be fetching individual memos iteratively in the first place. A user's list of memo ids will probably be removed in [#57](https://github.com/jerrydngzh/372.projdev/issues/57#issuecomment-2041667877).

Option 1 suggest to fetch the entire list of memos *each* time on load of the dashboard/lens/etc. and store it there to be used.

Option 2 suggests to get all the *first* time on App load, then only send over the network, requests that involve adding/deleting/updating individual items as they come, while maintaining the same list locally on the client.

There should still be a need to maintain a list (dashboard, lens) as that is how state will be stored and interacted with while on those pages. 

Creating a Memo shouldn't require a list in itself as there is no need for it. the operation is currently stateless and should just make the request to send data over.
