### ISSUE TITLE
Refactor dashboard list of locations // list of memos // popup

### ISSUE THREAD

**Issue by jerrydngzh** [jerrydngzh/372.projdev#62]
DO THIS BEFORE #61 

please refactor the dashboard and modularize components:
a suggested example file structure:
```tsx
Dashboard/
   components/
       LocationItem.tsx
       LocationMemoList.tsx
       Popup.tsx
   page.tsx
```
a logical flow of components and the component tree:
1. dashboard should render a list of locations -> pass in props to each location component a list of their memos
2. each location component should render their respective list of memos
3. each of those memos renders a popup

take a look at:
- https://react.dev/learn/rendering-lists
- https://github.com/jerrydngzh/recipe-app/tree/main/frontend/src/components

**Comment by Leepak777** [comment]
Yessir will work on it now
