### ISSUE TITLE
ui overhaul

### ISSUE THREAD

**Issue by jerrydngzh** [jerrydngzh/372.projdev#63]
motivation:
1. our user interface was something thrown together quickly back during iteration 1
2. there's another project with the same name & idea as us (so we assume), so we ought to one up them when we present on friday 😈
   ![image](https://github.com/jerrydngzh/372.projdev/assets/68207411/65add1bc-3f78-44ed-af9d-7af77e558686)

**Comment by vinn03** [comment]
yessir!!! ill thug this out all day tmr
