### ISSUE TITLE
setup & test connection to cloud storage bucket for media uploads

### ISSUE THREAD

**Issue by jerrydngzh** [jerrydngzh/372.projdev#75]
- backend service to upload images to google cloud storage

workflow:
1. client creates a memo
2. adds media (photos, videos, etc.)
3. send request to backend w/ memo data + image data
4. POST /memo handles creating a memo, send media data in body to media service 
5. media service uploads image data to cloud storage
6. returns to memo service names of files `uuid-file_name`, stored on cloud storage w/ structure `/uid/filename`

accessing images on client:
- viewing: 
  - take the cloud storage bucket url + filename
- editing:
   - adding -> normal workflow
   - deleting -> tba

**Comment by Toastjpg** [comment]
https://stackoverflow.com/questions/51410633/service-account-does-not-have-storage-objects-get-access-for-google-cloud-storag
